# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.


default:
  adapter: postgresql
  encoding: unicode
    # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
development:
  adapter: postgresql
  encoding: unicode
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
  database: smartrain_development
  password: '<%= ENV["DEVELOPMENT_DATABASE_PASSWORD"] %>' 
test:
  adapter: postgresql
  encoding: unicode
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
  database: smartrain_test
  password: '<%= ENV["TEST_DATABASE_PASSWORD"] %>' 
production:
  adapter: postgresql
  encoding: unicode
  pool: '<%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>'
  database: smartrain_production
  username: smartrain
  password: '<%= ENV["SMARTRAIN_DATABASE_PASSWORD"] %>'
